#+TITLE: 青空文庫修正計画
#+STARTUP: showall
#+AUTHOR: Taichi Kawabata <kawabata.taichi@gmail.com>

* 趣旨

  青空文庫は、著作権が切れたり、または著作者が自由配布を許可した、いわ
  ば公共に自由に配布可能な文学作品をボランティアによって電子化・インター
  ネット上で公開するプロジェクトです。

  残念ながら、青空文庫の本体では、人的にも資金的にもリソースが不足して
  いて、既存ファイルの誤植訂正がなかなか十分に行われていません。

  青空文庫のテキストには独自の注記記法が定められていますが、この注記記
  法はしばしば変更され、また変更後も青空文庫の古い作品は何も修正されま
  せん。そのため、現在の注記記法にしたがって作成された青空文庫リーダー
  は、古い作品を読むことができない場合があります。

  本プロジェクトは、既存の青空文庫作品において、明らかな誤植を修正した
  り、または現在の注記記法と大幅に異なる記法で注記が書かれ、機械的処理
  が困難と思われる古い作品を現在の記法へ修正することを目指します。

  これによって、より多くの青空文庫リーダで、古い作品も読めるようにし、
  また誤植を直していきます。この作業を通して、既存の青空文庫作品に対す
  るエラッタ情報を提供することを目指します。

* テキストの修正方法

  修正作業は、誰もが自由に行えることをめざし、gitで行います。gitは分散
  開発環境です。誰もが好きな人のレポジトリをフォークし、それを修正でき
  ます。修正したら、修正内容を反映して欲しい人に、反映をお願いすること
  ができます。（pull requestと言います。）

** 枝の種類

   aozora-fix では、以下の２種類の枝を管理します。

   - master :: 青空文庫から配布されるファイルを管理する枝
   - fix :: 青空文庫の間違い等を修正する枝

   ある程度、修正が蓄積された後は、青空文庫本枝との間のパッチファイルを
   作成し、個別に配布する予定です。

** 修正方法

   修正作業の希望者は、まずgithubのアカウントを取得してください。（以下、
   アカウント名をUSERNAMEとします。）その後、以下の手順で修正を行います。

   1. まずgithubにログインします。

   2. 修正したいレポジトリを持つ人のWebページに行って、右上の「fork」ボ
      タンを押します。すると、自分のアカウントに aozora-fix のデータが
      フォーク（分岐）されます。（以下、例としてkawabata/aozora-fixから
      フォークするとします。）
      : https://github.com/kawabata/aozora-fix

   3. 自分のホームページに行って、きちんとフォーク（分岐）が行われたか
      を確認します。
      : https://github.com/USERNAME/aozora-fix

   4. 自分のローカルマシンで、作業用ディレクトリを作成し、以下の命令を
      実行します。すると、自分のローカルマシンに青空文庫作品がダウンロードされます。
      : git clone https://USERNAME@github.com/USERNAME/aozora-fix
      : git clone git://github.com/USERNAME/aozora-fix

   5. ローカルマシンのブランチ状態を確認し、fixに切り替えます。
      : git branch （ブランチの状態の確認）
      : git checkout fix （fixブランチへ切り替え）

   6. 必要なファイルの修正を行います。

   7. 修正がある程度完了したら、現在の状況を確認し、修正ファイルをステー
      ジングします。
      : git status
      : git add

   8. 修正が蓄積されたら、ステージングされたファイルをまとめてローカル
      レポジトリにコミットします。
      : git commit

   9. 自分のローカルディレクトリの修正内容を、githubにプッシュします。
      : git push origin fix

   10. 必要に応じて、ホームページからマージして欲しい相手に pull
       requestを行います。

** 他人の修正のマージ方法

   1. マージしたい人のレポジトリを、自分のローカルマシンの作業ディレク
      トリに追加します。
      : git remote add -f USERNAME git://github.com/USERNAME/aozora-fix.git

   2. 追加したレポジトリの内容を、githubから読み込みます。
      : git checkout -b USERNAME/fix

   3. 再び作業ディレクトリを自分のブランチに戻します。
      : git checkout fix

   4. 修正内容を確認します。
      : git diff fix USERNAME/fix

   5. 修正をマージします。
      : git merge USERNAME/fix

   6. 修正をgithubに反映させます。
      : git push origin fix

* 注記記法の正確さの確認

  「漢字データベース」が提供する、青空文庫・注記記法の解析表現文法を用
  いて、注記が正しく書かれているかをチェックします。

* 作品ファイル名について

  青空文庫は基本的にzipで配布され、それを解答するとzipファイルとは異な
  るファイル名が生成されます。この名前を保存するため、たとえば

  : http://www.aozora.gr.jp/cards/000879/files/43386_ruby_25696.zip
  : （解凍すると `dekiagatta_hito.txt' が生成）

  という青空文庫の作品ファイルに対しては、

  : /000879/files/43386_ruby_25696/dekiagatta_hito.txt

  というファイルパス名で作業を行います。
